-- create database customer_behaviour;  
-- select *from customer limit 20
-- q1what  is the total revenue generated by the male vs female customer .
select gender ,sum(purchase_amount ) as revenue 
from customer 
group by gender;
--   Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id ,purchase_amount 
from customer
where  promo_code_used = 'yes' and purchase_amount >=(select avg(purchase_amount )from customer);
select *from customer  limit 20;
-- q3 what are the top 5 product with higest  average review rating 
select item_purchased ,round(avg(review_rating ),2) as "average_product_rating "
from customer 
group by item_purchased
order by avg(review_rating )desc
limit 10

SELECT  shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer 
group  by shiping_type;
select *from customer category
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers. 
select subscription_status ,
count(customer_id )as total_customer 
round(avg(purchase_amount ) )as avg_spend
round(sum(purchase_amount ))as total_revenue 
from customer 
group by subcription_status
order by total_revenue , avg_spend desc;
-- which 5 product have the higest percentage of purchase after discount applied 
select item_purchased,
       ROUND(100.0 * SUM(CASE WHEN promo_code_used = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 20;
-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as( 
select customer_id , previous_purchases,
CASE 
when previous_purchases = 1  then 'new'
when previous_purchases between 2 and 10 then 'regular'
else 'loyal'
end as customer_segment 
from customer )
select customer_segment ,count(*) as 'number_of_customer'
from customer_type  
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status ,count(customer_id )as repetative_buyer
from customer 
where previous_purchases  >5
group by subscription_status;
-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount ) as total_revenue 
from customer 
group by age_group 
order by total_revenue desc;



